apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: pg-test
  namespace: demo
  labels:
    app: postgresql
    environment: test
spec:
  clusterDefinitionRef: postgresql
  clusterVersionRef: postgresql-14.8.0
  terminationPolicy: Delete
  affinity:
    podAntiAffinity: Preferred
    topologyKeys:
      - kubernetes.io/hostname
  componentSpecs:
    - name: postgresql
      componentDefRef: postgresql
      serviceVersion: "14.8.0"
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "500m"
          memory: "512Mi"
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
