apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-snapshot-restore
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: pg-test-backup-001-0-data